### ISSUE TITLE
The working directory that configured in the service unit is wrong or inaccessible

### ISSUE THREAD

**Issue by ensarkarabudak** [sixfab/Sixfab_QMI_Installer#2]
https://github.com/sixfab/Sixfab_QMI_Installer/blob/9a0af0a2643f30ecdec478274f2118bd6e689af3/reconnect_sh#L11

Installation directory: `/opt/qmi_files/quectel-CM/`

Replace with: `sudo /opt/qmi_files/quectel-CM/quectel-CM -s #APN`

**Comment by saeedjohar** [comment]
WorkingDirectory=/opt/qmi_files/quectel-CM/ 

fixes it.
