### ISSUE TITLE
qmi_install.sh incompatible with 5.4.51-v7l+ kernel

### ISSUE THREAD

**Issue by mldichter** [sixfab/Sixfab_QMI_Installer#3]
qmi_install.sh can only accept 4.14 and 4.19, but the kernel has changed.

The “Getting Started” followed by the “QMI Interface with Cellular IoT App Shield” do not work as of this review. Step 10, “Run the installation file. Make sure the module is disconnected before running the installer script. sudo ./qmi_install.sh” results in “Driver for 5.4.51-v7l+ kernel not found” output.

The problem comes from the qmi_install.sh file in these lines,

```
case $(uname -r) in
    4.14*) echo $(uname -r) based kernel found
        echo "${YELLOW}Downloading source files${SET}"
        wget https://github.com/sixfab/Sixfab_RPi_3G-4G-LTE_Base_Shield/raw/master/tutorials/QMI_tutorial/src/4.14.zip -O drivers.zip
        unzip drivers.zip -d $INS_DIR && rm -r drivers.zip;;
    4.19*) echo $(uname -r) based kernel found 
        echo "${YELLOW}Downloading source files${SET}"
        wget https://github.com/sixfab/Sixfab_RPi_3G-4G-LTE_Base_Shield/raw/master/tutorials/QMI_tutorial/src/4.19.1.zip -O drivers.zip
        unzip drivers.zip -d $INS_DIR && rm -r drivers.zip;;
    *) echo "Driver for $(uname -r) kernel not found";exit 1;
esac
```

When will the installation files, or at least the instructions, be updated? As an alternative, can a compatible raspberry pi image be posted? If not, this product is not of much use anymore.

**Comment by dylanshuler11** [comment]
Just ran into the same issue getting the base hat up and running. While I hope they can update their drivers to work with the newest kernel, you can use the following command to revert to 4.19. 

'rpi-update 993f47507f287f5da56495f718c2d0cd05ccbc19`

**Comment by mldichter** [comment]
Thanks. I should also note that I was following the instructions for the Raspberry Pi 4, which skips steps 4-7 in the instructions.
