### ISSUE TITLE
Raspberry Pi 64bit OS Support

### ISSUE THREAD

**Issue by ImanolGo** [sixfab/Sixfab_QMI_Installer#8]
Hi, 

I'm currently running Raspberry Pi OS Lite (64-bit) Bullseye, and unfortunately I cannot find any compatible driver. Are you working on its support?

**Comment by ensarkarabudak** [comment]
Hi,

Compatible drivers have been added to the installation file. You can test it.

**Comment by ImanolGo** [comment]
@ensarkarabudak thanks for updating the script. Now it works fine. I somehow also realized the USB driver wasn't needed anymore.

**Comment by ensarkarabudak** [comment]
yep! it is already installed with the kernel.
